name: scanpy-app-backend
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - fastapi
  - uvicorn[standard]
  - scanpy>=1.9 # Ensure a recent version
  - python-multipart # For file uploads
  - celery>=5.0
  - redis-py     # Celery broker/backend client
  - redis        # Installs redis server via conda (convenient for local dev)
  - matplotlib
  - seaborn
  - pydantic
  - aiofiles     # For async file saving